# copy_file.yml

- name: copy files to destination
  hosts: all
  become: true
  tasks:
    - name: copy src.txt as dest.txt in the same dir 
      copy:
        src: home/ansadmin/index.html
        dest: home/ansadmin
      tags:
        - simple_copy
